### ISSUE TITLE
issue:  race condition issue

### ISSUE THREAD

**Issue by ltdrdata** [11cafe/comfyui-workspace-manager#175]
```
Exception in thread Thread-2 (populate_file_hash_dict):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/teratera/git/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 50, in populate_file_hash_dict
    for folder in folder_paths.folder_names_and_paths:
RuntimeError: dictionary changed size during iteration
```

This is the reason.
https://github.com/11cafe/comfyui-workspace-manager/blob/742b6834f77ec7c1b40effc8dd363063106e7032/service/model_manager/model_list.py#L94

Among the custom nodes, there are those that register additional paths in `folder_paths.folder_names_and_paths`. If such an event occurs while this code is running in thread, it can lead to the race condition issue mentioned above.
https://github.com/11cafe/comfyui-workspace-manager/blob/742b6834f77ec7c1b40effc8dd363063106e7032/service/model_manager/model_list.py#L50

**Comment by Weixuanf** [comment]
hi thanks very much for finding and investigating this issue! We'll have a fix soon, to make it thread safe operation.
