### ISSUE TITLE
IMPORT FAILED  What's wrong?

### ISSUE THREAD

**Issue by ctao233** [11cafe/comfyui-workspace-manager#222]
![图片](https://github.com/11cafe/comfyui-workspace-manager/assets/71979192/1f0ab2e2-a1ad-4232-bf24-871ee92ab8c9)

**Comment by Weixuanf** [comment]
Hi can you check the python server terminal and search for and “workspace-manager” related error log? You can screenshot if find anything suspicious
________________________________
From: ctao233 ***@***.***>
Sent: Thursday, February 29, 2024 11:04:50 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] IMPORT FAILED What's wrong? (Issue #222)


default.png (view on web)<https://github.com/11cafe/comfyui-workspace-manager/assets/71979192/1f0ab2e2-a1ad-4232-bf24-871ee92ab8c9>

**Comment by hurricanepilot** [comment]
I get the same thing after I install a new custom node in the manager and chose the restart option from the UI. 

Workaround is to Ctrl-C out of the comfyui process and restart manually, so not a big problem. 

To my untrained eye, it seems using the soft restart in the custom node manager doesn't result in a completely clean state for the next run, and a locked file is preventing import of the workspace manager?

relevant log:

```
Traceback (most recent call last):
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 13, in <module>
    from .service.model_manager.model_installer import download_url_with_wget
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
    from .model_list import start_populate_file_hash_dict, save_file_hash
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 20, in <module>
    file_hash_dict = shelve.open(FILE_HASH_DICT_PATH)
  File "/usr/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'

Cannot import /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
```

**Comment by Weixuanf** [comment]
> I get the same thing after I install a new custom node in the manager and chose the restart option from the UI.
> 
> Workaround is to Ctrl-C out of the comfyui process and restart manually, so not a big problem.
> 
> To my untrained eye, it seems using the soft restart in the custom node manager doesn't result in a completely clean state for the next run, and a locked file is preventing import of the workspace manager?
> 
> relevant log:
> 
> ```
> Traceback (most recent call last):
>   File "/home/jon/Development/AI/stable-diffusion/ComfyUI/nodes.py", line 1888, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 13, in <module>
>     from .service.model_manager.model_installer import download_url_with_wget
>   File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
>     from .model_list import start_populate_file_hash_dict, save_file_hash
>   File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 20, in <module>
>     file_hash_dict = shelve.open(FILE_HASH_DICT_PATH)
>   File "/usr/lib/python3.10/shelve.py", line 243, in open
>     return DbfilenameShelf(filename, flag, protocol, writeback)
>   File "/usr/lib/python3.10/shelve.py", line 227, in __init__
>     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
>   File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
>     return mod.open(file, flag, mode)
> _gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
> 
> Cannot import /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
> ```

hi thanks for providing the log, i just pushed a change in beta that may help this issue: https://github.com/11cafe/comfyui-workspace-manager/pull/328

if you know how to use git to switch to beta branch, can you try it and see if it resolves your issue? thank you!

**Comment by hurricanepilot** [comment]
Technically, the stated problem has gone, but so have the workspace manager UI elements in the top left.

for ref, I switched to beta:

```

**Comment by Weixuanf** [comment]
Sorry, I just pushed the build again to beta
You can try again thank you
________________________________

**Comment by hurricanepilot** [comment]
That seems to have done the trick. 

I ran through a a few install/uninstall loops for a couple of custom nodes and tried both a browser refresh and a close and re-open. All seems fine in terms of the UI and the logs.

**Comment by Weixuanf** [comment]
Cool! Thanks for testing! Is there any slow down in ui loading? Especially when opening the models drawer?
________________________________

**Comment by hurricanepilot** [comment]
There is a small (but perceptible) pause on initial load.

both videos are fresh browser starts, and show the first time opening the model menu:

[beta.webm](https://github.com/11cafe/comfyui-workspace-manager/assets/1544555/3158e43b-63a8-4885-8850-9b48062070e0)
[main.webm](https://github.com/11cafe/comfyui-workspace-manager/assets/1544555/d3fd9d36-5b9f-4a0d-a5c1-3f9e8aac11af)

**Comment by Weixuanf** [comment]
> There is a small (but perceptible) pause on initial load.
> 
> both videos are fresh browser starts, and show the first time opening the model menu:
> 
> [beta.webm](https://github.com/11cafe/comfyui-workspace-manager/assets/1544555/3158e43b-63a8-4885-8850-9b48062070e0) [main.webm](https://github.com/11cafe/comfyui-workspace-manager/assets/1544555/d3fd9d36-5b9f-4a0d-a5c1-3f9e8aac11af)

I see!! Thanks very much for testing, this is super helpful. I'll try to find a way that's less impactful on performance!

**Comment by Weixuanf** [comment]
hi @hurricanepilot  I just pushed another change to beta that may fix the perf AND the reboot issue, please see if it works, thank you!

**Comment by hurricanepilot** [comment]
Performance is much better, but sadly we're back to having the soft reboot issue :-(

```
Install custom node 'ComfyUI-RAVE'
install: ['https://github.com/spacepxl/ComfyUI-RAVE']
Download: git clone 'https://github.com/spacepxl/ComfyUI-RAVE'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18.0/18.0 [00:00<00:00, 22.52it/s]
Installation was successful.
After restarting ComfyUI, please refresh the browser.

...

Error opening shelve: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'. Attempting recovery...
Shelve file /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict unlocked successfully.
Traceback (most recent call last):
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 31, in open_shelve
    return shelve.open(path, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 13, in <module>
    from .service.model_manager.model_installer import download_url_with_wget
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
    from .model_list import start_populate_file_hash_dict, save_file_hash
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 50, in <module>
    file_hash_dict = open_shelve(FILE_HASH_DICT_PATH)
  File "/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 35, in open_shelve
    return shelve.open(path, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'

Cannot import /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'

...

Import times for custom nodes:
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-deepcache
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui_easy_padding
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/LoadLoraWithTags
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-image-round
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_Noise
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfy_clip_blip_node
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUi_NNLatentUpscale
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-portrait-master
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_Dave_CustomNode
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/WAS_Extras
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_VisualStylePrompting
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/lora-info
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-RAVE
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/OneButtonPrompt
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/clipseg.py
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_LayerStyle
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Flowty-LDSR
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Manager
   0.0 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui_segment_anything
   0.1 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.1 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.2 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/a-person-mask-generator
   0.2 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.8 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/ComfyUI-YoloWorld-EfficientSAM
   0.9 seconds: /home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by Weixuanf** [comment]
:(( what os are u using? Linux? Windows? I hope I could repro it, it would be easier for me to debug. But I tried in my macOS and Windows and can't repro ( I install a node from ComfyUI-Manager and click the restart button, refresh page, and workspace manager still appears)

**Comment by hurricanepilot** [comment]
> :(( what os are u using? Linux? Windows? I wish I could repro it, it would be easier for me to debug. But I tried in my macOS and Windows and can't repro ( I install a node from ComfyUI-Manager and click the restart button, refresh page, and workspace manager still appears)

I'm on Ubuntu 22.04

**Comment by Weixuanf** [comment]
hi i just pushed another change to beta that solves this issue...i'm not too sure if it has perf impact anymore. I think I'll just go with the solution for now until we find a better one..

**Comment by hurricanepilot** [comment]
For me, this has completely broken the model viewer. I get a "Resource temporarily unavailable" error for every single model (checkpoint, lora, etc.) as it's being enumerated, and results in the model view being empty.

I've also checked the main branch  and it isn't happenning there.

snippet from the log:
```
Error processing file: SD1.5/AnythingXL_inkBase.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/Inpainting/dreamshaper_8Inpainting.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/Inpainting/v1-5-pruned-inpainting.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/LCM/dreamshaper_8LCM.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/abyssorangemix3AOM3_aom3a1b.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/arthemyComics_v60Bakedvae.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/chilloutmix_NiPrunedFp32Fix.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/imp_v10.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/inkpunk-diffusion-v1.ckpt in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/majicmixFantasy_v30Vae.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/noosphere_v42.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/perfectdeliberate_v5.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/realisticVisionV51_v51VAE.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/realisticVisionV60B1_v60B1VAE.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/revAnimated_v122EOL.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/samaritan3dCartoon_samaritan3dCartoonV3.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/v1-5-pruned-emaonly.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/CHEYENNE_v16VAEBaked.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Inpainting/sdxl-inpaint.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Lightning/dreamshaperXL_lightningDPMSDE.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Lightning/duchaitenAiartSDXL_v33515LightningTCD.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Lightning/juggernautXL_v9Rdphoto2Lightning.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Lightning/leosamsHelloworldXL_hw50EulerALightning.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/Lightning/moonrideMixes_moonrideLightMix1.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/albedobaseXL_v21.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/animaPencilXL_v100.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/artium_v20.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/dynavisionXLAllInOneStylized_releaseV0610Bakedvae.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/ivisionIllustration_ivision10.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/juggernautXL_version6Rundiffusion.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SDXL/sdXL_v10VAEFix.safetensors in folder: checkpoints. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/1.5_perfect hands.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/Ghibli Style.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/HandFineTuning.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/IPAdapter/ip-adapter-faceid-plus_sd15_lora.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/IPAdapter/ip-adapter-faceid-plusv2_sd15_lora.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/LCM/lcm-lora-sd1.5.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/Sci-fi_Enviroments.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/add_more_details.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dungeon v1.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_13_water_reflections.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_27_from_above.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_32_fisheye_lens.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_33_bokeh_lighting.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_42_rim_light.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/dynamic_shot_53_two_colors_lighting.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/goodhands_Beta_Gtonero.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/lego_v2.0.768.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
Error processing file: SD1.5/lego_v2.0.safetensors in folder: loras. Error: [Errno 11] Resource temporarily unavailable: '/home/jon/Development/AI/stable-diffusion/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/../../hash/file_hash_dict'
...etc.
```

**Comment by Weixuanf** [comment]
@hurricanepilot hi it should be fixed now, in both main and beta. not too sure about the perf impact this time. But the reboot problem should be gone. Sorry for the inconvenience. It's hard for me to test and debug in linux..

**Comment by hurricanepilot** [comment]
I've just done a completely fresh install of ComfyUI and added the the workspace manager during setup (main branch). I've since installed numerous custom nodes, with frequent soft restarts, and the problem hasn't resurfaced.

**Comment by Weixuanf** [comment]
Sounds good! ☺️☺️
________________________________
