### ISSUE TITLE
Drag and Drop Error

### ISSUE THREAD

**Issue by EdKZoo** [11cafe/comfyui-workspace-manager#263]
I can't drag and drop workflows that have an reroute node in it. The workflows work fine when i open them, but nothing happens when i try to drag them into another workflow.
Pressing F12 i get this error in the console:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at rerouteNode.js:32:81
    at Array.map (<anonymous>)
    at RerouteNode.onConnectionsChange (rerouteNode.js:32:51)
    at LGraphNode.configure (litegraph.core.js:2521:12)
    at LGraph.configure (litegraph.core.js:2240:26)
    at LGraph.configure (app.js:1323:22)
    at LGraph.configure (reroutePrimitive.js:14:29)
    at LGraph.configure (snapToGrid.js:53:21)
    at Tp (App-cZxcRZX7.js:7:70389)
    at HTMLCanvasElement.O (RecentFilesDrawer-_ZhkOQfN.js:8:69048)

**Comment by Weixuanf** [comment]
@Xiahussheng can you share the workflow.json you are using for this TripoSR? it would be very helpful for us to debug! Thank you!

**Comment by Weixuanf** [comment]
hi i have pushed an update of fix. Please update to latest version and see if the problem goes away. If not, please comment with your workflow that's not working, and I'll debug from there. Thank you!
