### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by whmc76** [11cafe/comfyui-workspace-manager#365]
Error handling request
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311-master\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-master\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-master\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-master\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-master\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311-master\ComfyUI\custom_nodes\comfyui-workspace-manager\service\file_sync_service.py", line 179, in deduplicate_workflow_ids
    await asyncio.to_thread(dedupe_workflow_ids)
  File "asyncio\threads.py", line 25, in to_thread
  File "concurrent\futures\thread.py", line 58, in run
  File "E:\IMAGE\ComfyUI-base-py311-master\ComfyUI\custom_nodes\comfyui-workspace-manager\service\file_sync_service.py", line 175, in dedupe_workflow_ids
    check_and_update_workflow_id(file_path, seen_ids)
  File "E:\IMAGE\ComfyUI-base-py311-master\ComfyUI\custom_nodes\comfyui-workspace-manager\service\file_sync_service.py", line 139, in check_and_update_workflow_id
    json_data = json.load(f)
                ^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Weixuanf** [comment]
是不是有空的.json workflow文件？

**Comment by Weixuanf** [comment]
https://github.com/11cafe/comfyui-workspace-manager/pull/367

加了error catch了，你看看还有没有这个问题，控制台估计还是会输出有这么一个报错，但应该不影响使用。本质是因为你有workflow的json是空的，你把空的json给删了就不会报错了

**Comment by whmc76** [comment]
> #367
> 
> 加了error catch了，你看看还有没有这个问题，控制台估计还是会输出有这么一个报错，但应该不影响使用。本质是因为你有workflow的json是空的，你把空的json给删了就不会报错了

好滴 我看看可能是有空的

**Comment by whmc76** [comment]
你猜咋的 
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/129386342/a4dd9d3a-4476-4699-91b4-a225bdd89dec)

**Comment by Weixuanf** [comment]
😂😂嗯解析错误了
你是把你的my_workflows文件夹加了git版本控制了么

**Comment by whmc76** [comment]
哈哈对呀 不做备份不舒服



---Original---
From: "Weixuan ***@***.***&gt;
Date: Fri, May 10, 2024 16:25 PM
To: ***@***.***&gt;;
Cc: "Cyber Dick ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [11cafe/comfyui-workspace-manager] json.decoder.JSONDecodeError:Expecting value: line 1 column 1 (char 0) (Issue #365)




 
😂😂嗯解析错误了
 你是把你的my_workflows文件夹加了git版本控制了么
