### ISSUE TITLE
dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by darkmirrors** [11cafe/comfyui-workspace-manager#436]
今天用 conda 来统一环境，但是报这个错误，有头绪吗?
 
```
Traceback (most recent call last):
  File "/mnt/data0/work/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 16, in <module>
    from .service.model_manager.model_installer import *
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
    from .model_list import start_populate_file_hash_dict, save_file_hash
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 21, in <module>
    with shelve.open(FILE_HASH_DICT_PATH) as file_hash_dict_early_open:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available

Cannot import /mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: db type is dbm.gnu, but the module is not available
```

**Comment by Weixuanf** [comment]
ohh ok 我回头加个catch这里 你用的什么python版本
________________________________
From: darkmirrors ***@***.***>
Sent: Wednesday, July 10, 2024 6:03:29 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] dbm.error: db type is dbm.gnu, but the module is not available (Issue #436)


今天用 conda 来统一环境，但是报这个错误，有头绪吗?

Traceback (most recent call last):
  File "/mnt/data0/work/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 16, in <module>
    from .service.model_manager.model_installer import *
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
    from .model_list import start_populate_file_hash_dict, save_file_hash
  File "/mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 21, in <module>
    with shelve.open(FILE_HASH_DICT_PATH) as file_hash_dict_early_open:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/miniconda3/envs/py311/lib/python3.11/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available

Cannot import /mnt/data0/work/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: db type is dbm.gnu, but the module is not available


―

**Comment by Weixuanf** [comment]
噢我看到了你用的11，奇怪..没事 我回头加个catch吧这个不是必须要用的 主要是缓存models list
________________________________

**Comment by Icedcocon** [comment]
Same promblem.

```bash
Traceback (most recent call last):
  File "/root/ComfyUI/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/ComfyUI/custom_nodes/comfyui-workspace-manager/__init__.py", line 16, in <module>
    from .service.model_manager.model_installer import *
  File "/root/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_installer.py", line 13, in <module>
    from .model_list import start_populate_file_hash_dict, save_file_hash
  File "/root/ComfyUI/custom_nodes/comfyui-workspace-manager/service/model_manager/model_list.py", line 21, in <module>
    with shelve.open(FILE_HASH_DICT_PATH) as file_hash_dict_early_open:
  File "/opt/conda/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/opt/conda/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/opt/conda/lib/python3.10/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available

Cannot import /root/ComfyUI/custom_nodes/comfyui-workspace-manager module for custom nodes: db type is dbm.gnu, but the module is not available

```

**Comment by JHanley85** [comment]
I fixed this with git clean -xfd.
Looks like this happens with an update, and it just needs to get cleaned first.
