### ISSUE TITLE
[Bug]: When refreshing comfy, the loaded workflow does not show up as a loaded workflow

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [11cafe/comfyui-workspace-manager#452]
![image](https://github.com/user-attachments/assets/91574c4c-e27a-44da-947d-0c3e6e511d7a)

With the latest version of Comfy (updated ~2 days ago), it stops using workspace manager to "load" the previous workflow.

This means that the floating menu bar of workspace manager does not get the File-menu, which means that File > Save is not accessible. I have to Save anew, which creates a new workflow, or I have to load the previous workflow, which means my local changes are lost.

![image](https://github.com/user-attachments/assets/d276447d-6370-4806-8be5-f728701a701b)

And since copying nodes does not work on Firefox, it's a bit of a PITA to work with as I cannot transfer everything to the "new" save easily.

**Comment by Weixuanf** [comment]
have you updated the plugin to latest version? Can you F12 and screenshots some errors

**Comment by MNeMoNiCuZ** [comment]
I wasn't on the latest version it turns out, but I am now. 

Here are the lines from my console regarding workspace manager from my update and restart:

```
Updated: C:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager

Install: pip packages for 'C:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
 Collecting send2trash
   Downloading Send2Trash-1.8.3-py3-none-any.whl.metadata (4.0 kB)
 Downloading Send2Trash-1.8.3-py3-none-any.whl (18 kB)
 Installing collected packages: send2trash
 Successfully installed send2trash-1.8.3

Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)

   0.1 seconds: C:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager
```

However, I still get the same behavior.
I get the workflow loaded, but workspace manager thinks it's a new workflow and doesn't detect it as an existing one.



Here's a list of the F12 browser console error, I couldn't find anything about workspace manager.

```
Loading module from “http://127.0.0.1:8188/extensions/ComfyLiterals/operation-node.js” was blocked because of a disallowed MIME type (“text/plain”).
127.0.0.1:8188
Loading failed for the module with source “http://127.0.0.1:8188/extensions/dzNodes/dz_DZ_widgets.js”. 127.0.0.1:8188
Error loading extension /extensions/dzNodes/dz_debug.js TypeError: error loading dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js app.js:1454:22
Loading module from “http://127.0.0.1:8188/extensions/dzNodes/dz_DZ_widgets.js” was blocked because of a disallowed MIME type (“text/plain”).
127.0.0.1:8188
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data sidebar_node.js:40:13
[mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed imageFeed.js:87:15
Error calling extension 'DZ.widgets' method 'init' 
Object { error: ReferenceError }
 
Object { extension: {…} }
 
Object { args: [] }
app.js:271:15
Latest release version: v0.34.0 checkVersion_mixlab.js:12:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 4.7, "ram_total": 67871223808, "ram_used": 24715563008, "ram_used_percent": 36.4, "hdd_total": 4000045854720, "hdd_used": 2059213213696, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 17, "gpu_temperature": 45, "vram_total": 25769803776, "vram_used": 2337271808, "vram_used_percent": 9.069808324178059}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 3.3, "ram_total": 67871223808, "ram_used": 24697356288, "ram_used_percent": 36.4, "hdd_total": 4000045854720, "hdd_used": 2059213230080, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 4, "gpu_temperature": 44, "vram_total": 25769803776, "vram_used": 2337271808, "vram_used_percent": 9.069808324178059}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.3, "ram_total": 67871223808, "ram_used": 24785788928, "ram_used_percent": 36.5, "hdd_total": 4000045854720, "hdd_used": 2059214065664, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 43, "vram_total": 25769803776, "vram_used": 2337271808, "vram_used_percent": 9.069808324178059}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 5.3, "ram_total": 67871223808, "ram_used": 24787529728, "ram_used_percent": 36.5, "hdd_total": 4000045854720, "hdd_used": 2059214065664, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 44, "vram_total": 25769803776, "vram_used": 2333171712, "vram_used_percent": 9.053897857666016}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 5.3, "ram_total": 67871223808, "ram_used": 24778280960, "ram_used_percent": 36.5, "hdd_total": 4000045854720, "hdd_used": 2059214065664, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.1, "ram_total": 67871223808, "ram_used": 24783884288, "ram_used_percent": 36.5, "hdd_total": 4000045854720, "hdd_used": 2059214065664, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.4, "ram_total": 67871223808, "ram_used": 24772526080, "ram_used_percent": 36.5, "hdd_total": 4000045854720, "hdd_used": 2059212623872, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.0, "ram_total": 67871223808, "ram_used": 24731648000, "ram_used_percent": 36.4, "hdd_total": 4000045854720, "hdd_used": 2059212623872, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 4.1, "ram_total": 67871223808, "ram_used": 24730353664, "ram_used_percent": 36.4, "hdd_total": 4000045854720, "hdd_used": 2059212607488, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.7, "ram_total": 67871223808, "ram_used": 24894824448, "ram_used_percent": 36.7, "hdd_total": 4000045854720, "hdd_used": 2059212607488, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 7.4, "ram_total": 67871223808, "ram_used": 25426833408, "ram_used_percent": 37.5, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 46, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 9.1, "ram_total": 67871223808, "ram_used": 25584685056, "ram_used_percent": 37.7, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 44, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.2, "ram_total": 67871223808, "ram_used": 25159835648, "ram_used_percent": 37.1, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 43, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 9.7, "ram_total": 67871223808, "ram_used": 25321308160, "ram_used_percent": 37.3, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 43, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 10.0, "ram_total": 67871223808, "ram_used": 25469059072, "ram_used_percent": 37.5, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 43, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 12.2, "ram_total": 67871223808, "ram_used": 25535553536, "ram_used_percent": 37.6, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 7.2, "ram_total": 67871223808, "ram_used": 25372790784, "ram_used_percent": 37.4, "hdd_total": 4000045854720, "hdd_used": 2059213258752, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 2125160448, "vram_used_percent": 8.246707916259766}]}} Error: Unknown message type crystools.monitor
    createSocket http://127.0.0.1:8188/scripts/api.js:152
api.js:157:13
[3D Visualizer] Registering node: TripoSRViewer visualization.js:123:17
JsonToText jsonToText.js:9:21
ViewText viewText.js:9:21
PlayMusic playSound.js:7:21
Empty components: policy ignored components-manager.js:767:11
[🐍 pysssss] Skipping LinkRenderMode as core extension found linkRenderMode.js:9:12
Cookie “pinnedItems” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite utils.js:116:13
SidebarBoot sidebar_node.js:1278:17
execution time: 11949ms - timer ended sidebar_node.js:1279:17
SidebarPostBoot sidebar_node.js:1189:13
test sidebar_node.js:1212:17
#LoadImagesToBatch BasicGuider image_mixlab.js:864:15
#LoadImagesToBatch SamplerCustomAdvanced image_mixlab.js:864:15
#LoadImagesToBatch CLIPTextEncode image_mixlab.js:864:15
#LoadImagesToBatch KSamplerSelect image_mixlab.js:864:15
#LoadImagesToBatch VAELoader image_mixlab.js:864:15
#LoadImagesToBatch DualCLIPLoader image_mixlab.js:864:15
#LoadImagesToBatch VAEDecode image_mixlab.js:864:15
#LoadImagesToBatch Get Date Time String (JPS) 2 image_mixlab.js:864:15
#LoadImagesToBatch RandomNoise image_mixlab.js:864:15
#LoadImagesToBatch BasicScheduler image_mixlab.js:864:15
#LoadImagesToBatch Save Image w/Metadata image_mixlab.js:864:15
#LoadImagesToBatch EmptyLatentImage image_mixlab.js:864:15
#LoadImagesToBatch CM_SDXLResolution image_mixlab.js:864:15
#LoadImagesToBatch ImpactWildcardProcessor image_mixlab.js:864:15
#LoadImagesToBatch UNETLoader image_mixlab.js:864:15
apps 
Array []
ui_mixlab.js:1907:15
LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_categories/custom_categories.js sidebar_node.js:1097:29
LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_templates/custom_templates.js sidebar_node.js:1097:29
LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_workflows/custom_workflows.js sidebar_node.js:1097:29
The script from “http://127.0.0.1:8188/extensions/ComfyUI-N-Sidebar/panels/custom_categories/custom_categories.jsb?v=1722764322865” was loaded even though its MIME type (“application/octet-stream”) is not a valid JavaScript MIME type.
127.0.0.1:8188
The script from “http://127.0.0.1:8188/extensions/ComfyUI-N-Sidebar/panels/custom_templates/custom_templates.jsb?v=1722764322873” was loaded even though its MIME type (“application/octet-stream”) is not a valid JavaScript MIME type.
127.0.0.1:8188
The script from “http://127.0.0.1:8188/extensions/ComfyUI-N-Sidebar/panels/custom_workflows/custom_workflows.jsb?v=1722764322877” was loaded even though its MIME type (“application/octet-stream”) is not a valid JavaScript MIME type.
127.0.0.1:8188
custom category panel loaded custom_categories.jsb:805:13
custom workflow panel loaded custom_workflows.jsb:1338:17
custom template panel loaded custom_templates.jsb:1192:17
```

**Comment by Weixuanf** [comment]
if you use chrome will it work fine?

**Comment by MNeMoNiCuZ** [comment]
> if you use chrome will it work fine?

No. Also the same problem for me.

Here's the F12 console:
```
:8188/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/extensions/ComfyLiterals/operation-node.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1454 Error loading extension /extensions/ComfyLiterals/operation-node.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyLiterals/operation-node.js
(anonymous) @ app.js:1454
app.js:1454 Error loading extension /extensions/ComfyUI-Flowty-TripoSR/js/threeVisualizer.js TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".
(anonymous) @ app.js:1454
checkVersion_mixlab.js:12 Latest release version: v0.34.0
:8188/extensions/dzNodes/dz_DZ_widgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1454 Error loading extension /extensions/dzNodes/dz_debug.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js
(anonymous) @ app.js:1454
:8188/jovimetrix/config:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
sidebar_node.js:40 SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
imageFeed.js:87 [mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed
init @ imageFeed.js:87
:8188/DZ/debug:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:271 Error calling extension 'DZ.widgets' method 'init' Object Object Object
(anonymous) @ app.js:271
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 8.7, "ram_total": 67871223808, "ram_used": 34575372288, "ram_used_percent": 50.9, "hdd_total": 4000045854720, "hdd_used": 2059225104384, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 16342298624, "vram_used_percent": 63.41646512349447}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 13.1, "ram_total": 67871223808, "ram_used": 34318327808, "ram_used_percent": 50.6, "hdd_total": 4000045854720, "hdd_used": 2059225104384, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 16342298624, "vram_used_percent": 63.41646512349447}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 12.6, "ram_total": 67871223808, "ram_used": 34027466752, "ram_used_percent": 50.1, "hdd_total": 4000045854720, "hdd_used": 2059225169920, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 16342298624, "vram_used_percent": 63.41646512349447}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 12.2, "ram_total": 67871223808, "ram_used": 33843044352, "ram_used_percent": 49.9, "hdd_total": 4000045854720, "hdd_used": 2059225186304, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 35, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 16044232704, "vram_used_percent": 62.259817123413086}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 9.7, "ram_total": 67871223808, "ram_used": 33679212544, "ram_used_percent": 49.6, "hdd_total": 4000045854720, "hdd_used": 2059225186304, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 39, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 16046157824, "vram_used_percent": 62.26728757222494}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 10.2, "ram_total": 67871223808, "ram_used": 33543696384, "ram_used_percent": 49.4, "hdd_total": 4000045854720, "hdd_used": 2059225186304, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 15, "gpu_temperature": 41, "vram_total": 25769803776, "vram_used": 16046157824, "vram_used_percent": 62.26728757222494}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 9.7, "ram_total": 67871223808, "ram_used": 33743380480, "ram_used_percent": 49.7, "hdd_total": 4000045854720, "hdd_used": 2059225214976, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 3, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 15973806080, "vram_used_percent": 61.98652585347494}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 9.5, "ram_total": 67871223808, "ram_used": 33915400192, "ram_used_percent": 50.0, "hdd_total": 4000045854720, "hdd_used": 2059225235456, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 14, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 7.8, "ram_total": 67871223808, "ram_used": 33830543360, "ram_used_percent": 49.8, "hdd_total": 4000045854720, "hdd_used": 2059225247744, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 1, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 7.1, "ram_total": 67871223808, "ram_used": 33830023168, "ram_used_percent": 49.8, "hdd_total": 4000045854720, "hdd_used": 2059225280512, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 16, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.7, "ram_total": 67871223808, "ram_used": 33826844672, "ram_used_percent": 49.8, "hdd_total": 4000045854720, "hdd_used": 2059225280512, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 41, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.2, "ram_total": 67871223808, "ram_used": 33816936448, "ram_used_percent": 49.8, "hdd_total": 4000045854720, "hdd_used": 2059225280512, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 42, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 5.9, "ram_total": 67871223808, "ram_used": 33815556096, "ram_used_percent": 49.8, "hdd_total": 4000045854720, "hdd_used": 2059225296896, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 1, "gpu_temperature": 41, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.1, "ram_total": 67871223808, "ram_used": 34161446912, "ram_used_percent": 50.3, "hdd_total": 4000045854720, "hdd_used": 2059225296896, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 41, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
api.js:157 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 6.0, "ram_total": 67871223808, "ram_used": 34001563648, "ram_used_percent": 50.1, "hdd_total": 4000045854720, "hdd_used": 2059225296896, "hdd_used_percent": 51.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 0, "gpu_temperature": 41, "vram_total": 25769803776, "vram_used": 15973675008, "vram_used_percent": 61.98601722717285}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:152:18)
(anonymous) @ api.js:157
visualization.js:123 [3D Visualizer] Registering node: TripoSRViewer
jsonToText.js:9 JsonToText
beforeRegisterNodeDef @ jsonToText.js:9
viewText.js:9 ViewText
beforeRegisterNodeDef @ viewText.js:9
playSound.js:7 PlayMusic
beforeRegisterNodeDef @ playSound.js:7
components-manager.js:767 Empty components: policy ignored
rgthree.js:265 [rgthree] Blocked extension 'efficiency.widgethider' method 'nodeCreated' for rgthree-nodes because: Overrides value getter before widget getter is prepared. Can be lifted if/when https://github.com/jags111/efficiency-nodes-comfyui/pull/203 is pulled.
(anonymous) @ rgthree.js:265
linkRenderMode.js:9 [🐍 pysssss] Skipping LinkRenderMode as core extension found
view:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
view:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
sidebar_node.js:1278 SidebarBoot
sidebar_node.js:1279 execution time: 8798.22314453125 ms
:8188/userdata/workflows%2F.index.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/DZ/debug:1 
        
        
       Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/pysssss/autocomplete:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/easyuse/models/thumbnail:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
sidebar_node.js:1189 SidebarPostBoot
sidebar_node.js:1212 test
sidebar_node.js:1097 LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_categories/custom_categories.js
sidebar_node.js:1097 LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_templates/custom_templates.js
sidebar_node.js:1097 LOADING ../extensions/ComfyUI-N-Sidebar/panels/custom_workflows/custom_workflows.js
custom_workflows.jsb?v=1722765192364:1338 custom workflow panel loaded
custom_templates.jsb?v=1722765192364:1192 custom template panel loaded
custom_categories.jsb?v=1722765192363:805 custom category panel loaded
App-qo42s2ji.js:10 Error getting file <axUf0RYnXn1B_zl3kg5JU> at "MNeMiC\Auraflow.json" Workflow ID doesn't match
i @ App-qo42s2ji.js:10
image_mixlab.js:864 #LoadImagesToBatch ModelSamplingAuraFlow
image_mixlab.js:864 #LoadImagesToBatch CheckpointLoaderSimple
2image_mixlab.js:864 #LoadImagesToBatch CLIPTextEncode
image_mixlab.js:864 #LoadImagesToBatch ModelSamplingAuraFlow
image_mixlab.js:864 #LoadImagesToBatch EmptyLatentImage
image_mixlab.js:864 #LoadImagesToBatch VAEDecode
4image_mixlab.js:864 #LoadImagesToBatch Get Date Time String (JPS)
image_mixlab.js:864 #LoadImagesToBatch VAEDecode
image_mixlab.js:864 #LoadImagesToBatch SaveImageExtended
image_mixlab.js:864 #LoadImagesToBatch Image Comparer (rgthree)
image_mixlab.js:864 #LoadImagesToBatch ImpactWildcardProcessor
2image_mixlab.js:864 #LoadImagesToBatch CLIPTextEncode
image_mixlab.js:864 #LoadImagesToBatch ShowText|pysssss
2image_mixlab.js:864 #LoadImagesToBatch KSampler
image_mixlab.js:864 #LoadImagesToBatch CheckpointLoaderSimple
image_mixlab.js:864 #LoadImagesToBatch SaveImageExtended
image_mixlab.js:864 #LoadImagesToBatch CLIPTextEncode
image_mixlab.js:864 #LoadImagesToBatch EmptyLatentImage
ui_mixlab.js:1907 apps Array(0)
```


It does say this:

```
custom workflow panel loaded
custom_templates.jsb?v=1722765192364:1192 custom template panel loaded
custom_categories.jsb?v=1722765192363:805 custom category panel loaded
App-qo42s2ji.js:10 Error getting file <axUf0RYnXn1B_zl3kg5JU> at "MNeMiC\Auraflow.json" Workflow ID doesn't match
```

So it seems to be a bit more helpful.
