### ISSUE TITLE
bug report in autosave

### ISSUE THREAD

**Issue by wingaturumqi** [11cafe/comfyui-workspace-manager#53]
Error handling request
Traceback (most recent call last):
  File "D:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\aiohttp\web_protocol.py", line 434, in _handle_request
    resp = await request_handler(request)
  File "D:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\aiohttp\web_app.py", line 505, in _handle
    resp = await handler(request)
  File "D:\sd-webui-aki\sd-webui-aki-v4.4\python\lib\site-packages\aiohttp\web_middlewares.py", line 118, in impl
    return await handler(request)
  File "D:\sd-webui-aki\comfyui\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\sd-webui-aki\comfyui\ComfyUI\custom_nodes\comfyui-workspace-manager\__init__.py", line 234, in update_file
    file.write(json_str)

UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 38039: illegal multibyte sequence

my comfyui has node AIGODLIKE-ComfyUI-Translation,it can translate english to chinese

**Comment by Weixuanf** [comment]
hi i just pushed this change: https://github.com/11cafe/comfyui-workspace-manager/commit/051ace362d41a82c4b1639b3a7a1f972e11d9b16
you can try to update to the latest version to see if this resolves your problem! Let me know! Thanks

**Comment by wingaturumqi** [comment]
thks,It's OK now.
